export const projects = [
  {
    title: 'FEM Social Meadia Dashboard',
    description: "Using Html, Sass, Css custom variables and javascript I built this social media dashboard. This was a challenge from frontend mentor. It has the theme toggling feature between dark and light.",
      image: '/images/1.png',
      tags: ['SemanticHtml', 'CssGrid', 'Dart-sass', 'Javascript'],
    source: 'https://github.com/mizanmahi/fem-smdb-theme-toggler',
    visit: 'https://smdb-dark-light-theme.netlify.app/',
    id: 0,
  },
  {
    title: 'React Movies (API PROJECT)',
    description:"While building it I've learned many React & JavaScript topics, as well as how to read api documentation and use them for our needs. This was fun building it.",
    image: '/images/2.png',
    tags: ['React', 'TavaScript', 'Styled Components'],
    source: 'https://github.com/mizanmahi/react-movies-ts',
    visit: 'https://moviedb-reactjs.netlify.app/',
    id: 1,
  },
  {
    title: 'Moments Mern App (working on it)',
    description: "This is mern project in which I'am currently working on as a pratise project. By building this I am learnig so many advanced feature of node, express and mongo and also the meretial UI.",
      image: '/images/3.png',
      tags: ['React', 'Node', 'Express', 'Mongo', 'Material Ui'],
    source: 'https://github.com/mizanmahi/mern-moments-app',
    visit: 'https://moments-mern-app-bymahi.netlify.app/',
    id: 2,
  },
  {
    title: 'Shomin React App',
    description: "This is an ecommerce application built by React, redux and firebase and many more frontend tools. This is also a practise project. And I learned so many new topics while building this project.",
    image: '/images/4.png',
    tags: ['React', 'Redux', 'Redux-saga', 'Firebase'],
    source: 'https://github.com/mizanmahi/shomin-react-app',
    visit: 'https://shomin-live.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Shomin Html and Css Template',
    description: "This is a fully responsive html template built using just only semantic Html and modern Css features like animation and flexbox.",
    image: '/images/5.png',
    tags: ['Html', 'Css', 'Css Animation'],
    source: 'https://github.com/mizanmahi/shomin',
    visit: 'https://mizanmahi.github.io/shomin/',
    id: 3,
  },
  {
    title: 'React Task App',
    description: "This is a react todo like task app. I created this for practising context api of react. It has some cool functionality. User can create and delete tasks",
    image: '/images/6.png',
    tags: ['React'],
    source: 'https://github.com/mizanmahi/react-task-app',
    visit: 'https://react-task-live.herokuapp.com/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];